server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mariadb://localhost:3306/QSH
    username: root
    password: 1308huang
    driver-class-name: org.mariadb.jdbc.Driver





